### ISSUE TITLE
Target configuration error when create subsystems

### ISSUE THREAD

**Issue by FuchengDum** [zrlio/jNVMf#16]
Hello 

I plan to play the software on HW, but there is some problem about target configuration when used nvmetcli. it occurs errors:

/ports/1/subsystems> create nqn.2019-08.com.dumnet:test
Could not symlink nqn.2019-08.com.dumnet:test in configFS: [Errno 2] No such file or directory

Would you please help me ?

Thanks
-------------------------------------------
sudo nvmetcli
/ports/1/subsystems> cd /
/> ls
o- / ..................................... [...]
  o- hosts ............................... [...]
  o- ports ............................... [...]
  | o- 1 ................................. [...]
  |   o- referrals ....................... [...]
  |   o- subsystems ...................... [...]
  o- subsystems .......................... [...]
    o- nqn.2019-08.com.dumnet:test ....... [...]
      o- allowed_hosts ................... [...]
      o- namespaces ...................... [...]
        o- 1 ............................. [...]
/> cd /ports/subsystems
No such path /ports/subsystems
/> cd /ports/1/subsystems
/ports/1/subsystems> ls
o- subsystems ............................ [...]
/ports/1/subsystems> create nqn.2019-08.com.dumnet:test
Could not symlink nqn.2019-08.com.dumnet:test in configFS: [Errno 2] No such file or directory

-------------------------------------------
lsmod | grep nvme
nvme_rdma              32768  0
nvme_fabrics           24576  1 nvme_rdma
nvmet_rdma             28672  0
nvmet                  61440  7 nvmet_rdma
rdma_cm                69632  5 ib_iser,nvme_rdma,rpcrdma,rdma_ucm,nvmet_rdma
configfs               45056  3 rdma_cm,nvmet
ib_core               258048  13 ib_iser,ib_cm,rdma_cm,ib_umad,nvme_rdma,ib_uverbs,rpcrdma,bnxt_re,ib_ipoib,iw_cm,mlx5_ib,rdma_ucm,nvmet_rdma
nvme                   40960  1
nvme_core              90112  5 nvme_fabrics,nvme_rdma,nvme
-------------------------------------------

**Comment by PepperJo** [comment]
Sorry I cannot help you since I do not use `nvmetcli` to setup targets. I follow more or less this documentation: https://community.mellanox.com/s/article/howto-configure-nvme-over-fabrics#jive_content_id_NVME_Target_Configuration

**Comment by FuchengDum** [comment]
Thanks for your time, I will try it again!

**Comment by FuchengDum** [comment]
Hello

would you please help me to do Latency and IOPS measurements. 

The real HW was used to test Latency. Could you give some examples? And It get errors when follow the below command :

-------------------------------
fio -filename=/dev/nvme7n1p1 -direct=1 -rw=read -ioengine=libaio -iodepth=16 -bs=8k -size 10G -numjobs=1 -runtime=30 -group_reporting -name=dum
fio: engine libaio not loadable
fio: engine libaio not loadable
fio: failed to load engine

---------------
rpm -qa | grep libaio
libaio1-0.3.109-17.15.x86_64
--------
fio -version
fio-3.15
--------------
rpm -qa | grep libaio
libaio1-0.3.109-17.15.x86_64

Thanks

**Comment by PepperJo** [comment]
Please only discuss problems/questions for jNVMf here. There are better suited forums for these kind of questions. Thanks!
