### ISSUE TITLE
if this project support SGL  RDMA read and write model now?

### ISSUE THREAD

**Issue by gwnet** [zrlio/jNVMf#19]
or only inline send model?
I feel RDMA read /write with SGL support is better for large IO.

**Comment by PepperJo** [comment]
@gwnet jNVMf always supported SGLs.

**Comment by gwnet** [comment]
man, 
Could you please point to me the code for RDMA read/write with SGL?

**Comment by PepperJo** [comment]
The example in the README uses SGLs!
