### ISSUE TITLE
can you create one simple read/write example application

### ISSUE THREAD

**Issue by gwnet** [zrlio/jNVMf#20]
I like one simple read/write application to start integrate with my application. can you write one for us?
benchmark is a little complex, and cannot very easily figure out the things. can we wrapper just one nvmehost class that provide read and write and trim API?

**Comment by PepperJo** [comment]
The example in the README should be simple enough? Let me know what you have problems with and we figure it out from there.

**Comment by gwnet** [comment]
ah, Yes you updated the readme, it is simple. :) can you create one .java file for it? :)
I can test it on my day.

**Comment by gwnet** [comment]
I remember Spark use this project, right? can you point to me the spark branch that use this? or other sample reference?

**Comment by gwnet** [comment]
Yes, I already setup one remote live debug environment, I think I can figure out readme sample soon. I will start work on it next day. BTW, can you share me the sample code link either spark or other project use jNVMf?

**Comment by PepperJo** [comment]
Check the code here: https://github.com/apache/incubator-crail/tree/master/storage-nvmf/src/main/java/org/apache/crail/storage/nvmf
It uses jNVMf and Crail can be used with Spark (e.g. shuffle engine or as input/output via HDFS API).

**Comment by gwnet** [comment]
looks like this sample does not include read/write code?
