### ISSUE TITLE
our nvme target subsystem nqn name is just one UUID string, not following NVMe spec strictly

### ISSUE THREAD

**Issue by gwnet** [zrlio/jNVMf#21]
can you point to me where to change code, to make jNVMf can connect to this kind of target. 
I know for now, jNVMf only connect standard nqn subsystem name with correct format. how can I work around this? can you change the code or point to me the code?

**Comment by PepperJo** [comment]
check out the validate method here: https://github.com/zrlio/jNVMf/blob/master/src/main/java/com/ibm/jnvmf/NvmeQualifiedName.java

**Comment by PepperJo** [comment]
Remove the body of the method and no NQN will be validated

**Comment by gwnet** [comment]
great. I see that. :) thank you so much!~
